import type {
	MotionGrammarAuthoringInstanceDescriptor,
	MotionGrammarAuthoringInstanceReference,
	MotionGrammarAuthoringProfileDescriptor,
} from "./authoring-profile";

export type MotionGrammarSystemMapBucketId =
	| "editable-scene"
	| "generated-scene"
	| "presentation-artifact";

export type MotionGrammarSystemMapBucket = {
	readonly id: MotionGrammarSystemMapBucketId;
	readonly label: string;
	readonly shortLabel: string;
	readonly summary: string;
	readonly count: number;
	readonly editableCount: number;
	readonly replaceableCount: number;
	readonly runtimeOnly: boolean;
	readonly nodeIds: readonly string[];
	readonly artifactIds: readonly string[];
	readonly slots: readonly MotionGrammarAuthoringInstanceDescriptor[];
};

export type MotionGrammarSystemMap = {
	readonly bindingId: string;
	readonly totalSlots: number;
	readonly editableSceneSlots: number;
	readonly generatedSceneSlots: number;
	readonly presentationArtifactSlots: number;
	readonly replaceableSlots: number;
	readonly runtimeOnlySlots: number;
	readonly buckets: readonly MotionGrammarSystemMapBucket[];
};

const BUCKET_ORDER = [
	"editable-scene",
	"generated-scene",
	"presentation-artifact",
] as const satisfies readonly MotionGrammarSystemMapBucketId[];

const bucketIdForReference = (
	reference: MotionGrammarAuthoringInstanceReference,
): MotionGrammarSystemMapBucketId => {
	switch (reference.kind) {
		case "scene-node":
			return "editable-scene";
		case "generated-scene-node":
			return "generated-scene";
		case "presentation-artifact":
			return "presentation-artifact";
	}
};

const bucketText = (
	id: MotionGrammarSystemMapBucketId,
): Pick<
	MotionGrammarSystemMapBucket,
	"label" | "runtimeOnly" | "shortLabel" | "summary"
> => {
	switch (id) {
		case "editable-scene":
			return {
				label: "Editable scene objects",
				shortLabel: "Objects",
				summary:
					"Real scene nodes that stay in Layers and can be selected, styled, moved, or replaced.",
				runtimeOnly: false,
			};
		case "generated-scene":
			return {
				label: "Generated support objects",
				shortLabel: "Support",
				summary:
					"Scene nodes generated by the motion profile. They support the technique and are not primary replacement targets.",
				runtimeOnly: false,
			};
		case "presentation-artifact":
			return {
				label: "Runtime presentation artifacts",
				shortLabel: "Runtime",
				summary:
					"Runtime-only draw artifacts such as delayed echoes. They are not duplicated in Layers.",
				runtimeOnly: true,
			};
	}
};

const nodeIdForReference = (
	reference: MotionGrammarAuthoringInstanceReference,
): string | null => {
	switch (reference.kind) {
		case "scene-node":
		case "generated-scene-node":
			return reference.nodeId;
		case "presentation-artifact":
			return null;
	}
};

const artifactIdForReference = (
	reference: MotionGrammarAuthoringInstanceReference,
): string | null =>
	reference.kind === "presentation-artifact" ? reference.artifactId : null;

const makeBucket = (
	id: MotionGrammarSystemMapBucketId,
	slots: readonly MotionGrammarAuthoringInstanceDescriptor[],
): MotionGrammarSystemMapBucket => {
	const text = bucketText(id);
	return {
		id,
		...text,
		count: slots.length,
		editableCount: slots.filter((slot) => slot.editable).length,
		replaceableCount: slots.filter((slot) => slot.replaceable).length,
		nodeIds: slots.flatMap((slot) => {
			const nodeId = nodeIdForReference(slot.reference);
			return nodeId ? [nodeId] : [];
		}),
		artifactIds: slots.flatMap((slot) => {
			const artifactId = artifactIdForReference(slot.reference);
			return artifactId ? [artifactId] : [];
		}),
		slots,
	};
};

/**
 * Builds the shared semantic map used by Inspector, Timeline, and future
 * replacement surfaces. It keeps Layers responsible for real scene nodes while
 * making generated support and runtime presentation artifacts visible as motion
 * roles rather than fake layer rows.
 */
export function buildMotionGrammarSystemMap(
	profile: MotionGrammarAuthoringProfileDescriptor,
): MotionGrammarSystemMap {
	const byBucket = new Map<
		MotionGrammarSystemMapBucketId,
		MotionGrammarAuthoringInstanceDescriptor[]
	>();
	for (const slot of profile.roleSlots) {
		const bucketId = bucketIdForReference(slot.reference);
		const slots = byBucket.get(bucketId) ?? [];
		slots.push(slot);
		byBucket.set(bucketId, slots);
	}
	const buckets = BUCKET_ORDER.flatMap((bucketId) => {
		const slots = byBucket.get(bucketId) ?? [];
		return slots.length > 0 ? [makeBucket(bucketId, slots)] : [];
	});
	return {
		bindingId: profile.bindingId,
		totalSlots: profile.roleSlots.length,
		editableSceneSlots: byBucket.get("editable-scene")?.length ?? 0,
		generatedSceneSlots: byBucket.get("generated-scene")?.length ?? 0,
		presentationArtifactSlots:
			byBucket.get("presentation-artifact")?.length ?? 0,
		replaceableSlots: profile.roleSlots.filter((slot) => slot.replaceable)
			.length,
		runtimeOnlySlots: byBucket.get("presentation-artifact")?.length ?? 0,
		buckets,
	};
}
