import type { MotionDocument } from "@/entities/motion/model/types";
import type { MotionGrammarStoreDocument } from "@/entities/motion-grammar/model/command";
import type { SceneDocument } from "@/entities/scene/model/types";

/**
 * Visibility tier for a reference scene. Mirrors the product-update vocabulary
 * (`public`/`beta`/`internal`) without importing from `pages/` (which would be
 * an upward import); a future refactor can lift the shared union into `shared/`.
 */
export type ReferenceSceneStatus = "public" | "beta" | "internal";

/**
 * Catalog metadata for one reference scene. The executable payload (serialized
 * scene + motion) lives in `../fixtures`; this is the browsable, navigable layer
 * the tutorial gallery renders. `slug` is the foreign key tying the entry to its
 * `docs/product-knowledge/<slug>.md` how-to so tutorial copy is never duplicated
 * here, only referenced.
 */
export type ReferenceSceneMeta = {
	readonly slug: string;
	/** User-facing "what you will make" headline (English-first public copy). */
	readonly title: string;
	/** One-line English summary shown on the gallery card. */
	readonly summary: string;
	/** Grouping label for the gallery (e.g. "Motion"). */
	readonly category: string;
	readonly status: ReferenceSceneStatus;
	/**
	 * Frame sampled for the static gallery thumbnail. Pick a frame where the
	 * scene's motion has visibly displaced so the poster reads as motion, not a
	 * dead first frame.
	 */
	readonly posterFrame: number;
	/** `docs/product-knowledge/` filename that owns the canonical how-to prose. */
	readonly productKnowledge: string;
	/**
	 * Path (relative to `/tutorial-exports/`) to this scene's standalone "View
	 * export result" page — the genuine `editable`-profile motion/code export
	 * artifact (`createMotionCodeHtmlAsset`/`createMotionCodeRuntimeAsset`)
	 * regenerated by `gen:reference-scenes` into `public/tutorial-exports/`, not
	 * a bespoke demo renderer. `check:reference-scenes` verifies the file
	 * exists, is non-trivially sized, and its referenced runtime sibling
	 * exists.
	 */
	readonly exportDemo: string;
};

/**
 * A reference fixture rehydrated into live editor documents. `scene` and
 * `motion` feed the read-only SVG preview and (in a later slice) the editor load
 * path; `grammar` is the parsed `{bindings, passthrough}` the motion-grammar
 * store loads, kept in lockstep with the motion side-car.
 */
export type ResolvedReferenceScene = {
	readonly scene: SceneDocument;
	readonly motion: MotionDocument;
	readonly grammar: MotionGrammarStoreDocument;
};
