import {
	type LookGraph,
	type LookGraphNodeKind,
	type LookGraphOwnerRef,
	lookGraphNodeLabel,
	normalizeLookGraph,
} from "@/entities/scene/model/look-graph";
import type { LookGraphPlan } from "@/entities/scene/model/look-graph-compile";
import { createDctlSourceBuilder } from "@/shared/dctl";
import {
	CHAIN_SIGNATURE_PARAMS,
	chainCall,
	chainFnName,
	ROOT_FN_NAME,
} from "./chain";
import { lookDctlEmitters } from "./emitters/registry";
import { DCTL_HELPER_CLAMP_INT } from "./helpers";
import { DCTL_TAP_BUDGET } from "./tap-budget";
import type { LookDctlFidelity, LookDctlReport } from "./types";

/** Always-present document-level note per the plan's color-space contract. */
const COLORSPACE_ASSUMED_NOTE =
	"dctl-colorspace-assumed: input is treated as display-referred sRGB / Rec.709; wrap with a Color Space Transform if your footage is in a different working space.";

/**
 * Always-present document-level note (S2+): several uv-remap emitters
 * (`lens`, `kaleidoscope`, `flow`'s bulge/twist patterns, `warp`) interpret
 * their authored centre as "normalized 0..1 down the frame" (top = 0), which
 * only matches `uv` built from `transform()`'s `p_X`/`p_Y` if DCTL's `p_Y = 0`
 * is the top row — the standard video-frame scanline convention this
 * exporter assumes, mirroring the root sampler's unflipped `uv.y * p_Height`
 * indexing already established in S1's `lk_source`. If a given Resolve/GPU
 * pipeline uses a bottom-origin `p_Y`, centred/angular uv-remap nodes mirror
 * vertically.
 */
const UV_ORIENTATION_ASSUMED_NOTE =
	"dctl-uv-orientation-assumed: uv.y = 0 is treated as the top of the frame (p_Y = 0 = top row), matching this project's authored centre/angle conventions for Lens, Kaleidoscope, Flow, and Warp.";

/**
 * Present only when the export includes a `vhs-tracking`/`vhs-noise` (S4a)
 * or `signal-glitch`/`interlace` (S4b) node: all four drive their per-frame
 * animation from Resolve's `TIMELINE_FRAME_INDEX` global rather than a live
 * UI slider, since their `speed` bakes as a DCTL constant at export time
 * (matching every other multi-field node's hero/baked split) — see those
 * emitters' doc comments.
 */
const TIMELINE_FRAME_INDEX_NOTE =
	"dctl-timeline-frame-index-required: VHS Tracking/VHS Noise/Signal Glitch/Interlace animate using Resolve's TIMELINE_FRAME_INDEX global (Resolve 19.1+); older Resolve builds without this global will fail to compile the generated .dctl.";

const rootSamplerSource = (): string =>
	[
		`__DEVICE__ float3 ${ROOT_FN_NAME}(${CHAIN_SIGNATURE_PARAMS}) {`,
		"\tint x = lk_clamp_int(int(uv.x * float(p_Width)), 0, p_Width - 1);",
		"\tint y = lk_clamp_int(int(uv.y * float(p_Height)), 0, p_Height - 1);",
		"\tfloat r = _tex2D(p_TexR, x, y);",
		"\tfloat g = _tex2D(p_TexG, x, y);",
		"\tfloat b = _tex2D(p_TexB, x, y);",
		"\treturn make_float3(r, g, b);",
		"}",
	].join("\n");

const passthroughSource = (
	fnName: string,
	upstreamFnName: string,
	comment?: string,
): string => {
	const lines = [`__DEVICE__ float3 ${fnName}(${CHAIN_SIGNATURE_PARAMS}) {`];
	if (comment) lines.push(`\t// ${comment}`);
	lines.push(`\treturn ${chainCall(upstreamFnName)};`, "}");
	return lines.join("\n");
};

const transformEntrySource = (upstreamFnName: string): string =>
	[
		"__DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, __TEXTURE__ p_TexR, __TEXTURE__ p_TexG, __TEXTURE__ p_TexB) {",
		"\tfloat2 uv = make_float2((float(p_X) + 0.5) / float(p_Width), (float(p_Y) + 0.5) / float(p_Height));",
		`\treturn ${upstreamFnName}(p_TexR, p_TexG, p_TexB, p_Width, p_Height, uv);`,
		"}",
	].join("\n");

const exactFidelity = (
	nodeId: string,
	kind: LookGraphNodeKind,
): LookDctlFidelity => ({
	nodeId,
	kind,
	status: "exact",
});

const issueFidelity = (
	nodeId: string,
	kind: LookGraphNodeKind,
	status: "approx" | "unsupported",
	reason: string,
): LookDctlFidelity => ({ nodeId, kind, status, reason });

const formatFidelityLine = (entry: LookDctlFidelity): string =>
	entry.status === "exact"
		? `//   ${lookGraphNodeLabel(entry.kind)} (${entry.nodeId}): exact`
		: `//   ${lookGraphNodeLabel(entry.kind)} (${entry.nodeId}): ${entry.status} — ${entry.reason}`;

const ownerLabel = (owner: LookGraphOwnerRef): string => {
	switch (owner.scope) {
		case "scene":
			return "scene";
		case "artboard":
			return `artboard:${owner.artboardId}`;
		case "node":
			return `node:${owner.nodeId}`;
		case "scoped-overlay":
			return `scoped-overlay:${owner.scopedLookId} (artboard:${owner.artboardId})`;
	}
};

const buildHeaderComment = (
	owner: LookGraphOwnerRef,
	report: LookDctlReport,
): string => {
	const approxCount = report.nodes.filter(
		(entry) => entry.status === "approx",
	).length;
	const unsupportedCount = report.nodes.filter(
		(entry) => entry.status === "unsupported",
	).length;
	const lines = [
		"// Generated by Vecmo — Look Graph -> DCTL exporter.",
		`// Look owner: ${ownerLabel(owner)}`,
		"//",
		"// Color space: this DCTL assumes display-referred sRGB / Rec.709 input.",
		"// Wrap it with a Color Space Transform (CST) in the Resolve node graph if",
		"// your footage is not already in that space:",
		'//   input CST:  <camera/working space> -> sRGB ("Rec.709 gamma" practical)',
		"//   output CST: sRGB -> <your delivery/working space>",
		"//",
		`// Fidelity summary: ${report.nodes.length} node(s) total, ${approxCount} approximated, ${unsupportedCount} unsupported.`,
		`// Tap-budget guard: worst-case ${report.tapBudget.worstCaseProduct} of ${report.tapBudget.budget} taps (gather nodes multiply upstream chain evaluations; over-budget nodes degrade instead of failing the export).`,
		...report.notes.map((note) => `//   note: ${note}`),
		"//",
		"// Per-node fidelity:",
		...report.nodes.map(formatFidelityLine),
	];
	return lines.join("\n");
};

export type LookDctlLowerResult = {
	readonly source: string;
	readonly report: LookDctlReport;
};

/**
 * Lowers a compiled Look Graph plan into a complete `.dctl` source string. The
 * closure chain walks `plan.nodes` (already topologically ordered by
 * {@link import("@/entities/scene/model/look-graph-compile").compileLookGraph})
 * and mints one `__DEVICE__ float3 lk_node_<i>(...)` function per node,
 * threading the same pixel-name → function-name map `compileLookGraph` used
 * for its SVG `result` names so the two lowerings stay topologically
 * identical. A node either has a registered emitter (S1 pointwise:
 * `posterize`, `scanline`, `color-map`, `colorama`; S2 uv-remap/gather:
 * `warp`, `lens`, `kaleidoscope`, `wave-warp`, `bend-warp`, `flow`,
 * `displace`, `chromatic-fringe`; S3 gather: `blur`, `find-edges`,
 * `halftone`, `pixel-grid`, `ordered-dither`, `ascii-glyph`, `block-mosaic`,
 * `riso`, `grain`; S4a VHS pack: `vhs-color`, `vhs-tracking`, `vhs-noise`;
 * S4b CRT/glitch pack: `crt-display`, `signal-glitch`, `interlace`), is
 * disabled, or is `source`/`output` — all of which
 * become an identity pass-through function — or is an unsupported kind,
 * which also becomes a pass-through but is flagged `unsupported` in the
 * fidelity report (never silently dropped). Also runs the S3 tap-budget
 * guard: every pass-through counts as a 1-tap node, every emitted node
 * reports its own `tapCount`, and this function multiplies each node's tap
 * count against its upstream chain's accumulated product to size the next
 * gather node's {@link import("./types").LookDctlChainContext.tapBudget} and
 * to compute the report's overall `tapBudget.worstCaseProduct`.
 */
export function lowerLookGraphToDctl(
	graph: LookGraph,
	plan: LookGraphPlan,
	options: {
		readonly owner: LookGraphOwnerRef;
		/** S5 "expose all numeric parameters" export option; default off (hero params only), matching every emitter's pre-S5 behavior. */
		readonly exposeAllParams?: boolean;
	},
): LookDctlLowerResult {
	const normalized = normalizeLookGraph(graph) ?? graph;
	const nodeById = new Map(
		normalized.nodes.map((node) => [node.id, node] as const),
	);
	const builder = createDctlSourceBuilder();
	builder.addHelper(DCTL_HELPER_CLAMP_INT);

	const bodySections: string[] = [rootSamplerSource()];
	const pixelToFnName = new Map<string, string>([[plan.input, ROOT_FN_NAME]]);
	const fidelityNodes: LookDctlFidelity[] = [];
	// S3 tap-budget guard: the worst-case number of times `lk_source` would be
	// evaluated if every closure actually ran, tracked per pixel (`1` at the
	// chain root) and multiplied forward by each node's own tap count.
	const tapProductByPixel = new Map<string, number>([[plan.input, 1]]);
	let worstCaseTapProduct = 1;
	// S4a: set when a `vhs-tracking`/`vhs-noise` node actually emits — gates
	// the TIMELINE_FRAME_INDEX document note (see its doc comment above).
	let usesTimelineFrameIndex = false;

	plan.nodes.forEach((compiled, index) => {
		const fnName = chainFnName(index);
		const upstreamPixel =
			compiled.inputs.image ?? compiled.inputs.base ?? plan.input;
		const upstreamFnName = pixelToFnName.get(upstreamPixel) ?? ROOT_FN_NAME;
		const upstreamTapProduct = tapProductByPixel.get(upstreamPixel) ?? 1;
		const recordTapProduct = (pixel: string, tapCount: number): void => {
			const product = upstreamTapProduct * Math.max(1, tapCount);
			tapProductByPixel.set(pixel, product);
			worstCaseTapProduct = Math.max(worstCaseTapProduct, product);
		};
		const node = nodeById.get(compiled.nodeId);

		if (!node) {
			// Defensive: a cyclic/unresolved node compileLookGraph could not lower.
			bodySections.push(
				passthroughSource(
					fnName,
					upstreamFnName,
					`node ${compiled.nodeId} could not be resolved (cycle or missing definition); passed through unchanged`,
				),
			);
			fidelityNodes.push(
				issueFidelity(
					compiled.nodeId,
					compiled.kind,
					"unsupported",
					"dctl-node-unresolved: node participates in a cycle and was not compiled",
				),
			);
			pixelToFnName.set(compiled.output, fnName);
			recordTapProduct(compiled.output, 1);
			return;
		}

		if (!node.enabled) {
			bodySections.push(passthroughSource(fnName, upstreamFnName));
			fidelityNodes.push(exactFidelity(node.id, node.kind));
			pixelToFnName.set(compiled.output, fnName);
			recordTapProduct(compiled.output, 1);
			return;
		}

		if (node.kind === "source" || node.kind === "output") {
			bodySections.push(passthroughSource(fnName, upstreamFnName));
			fidelityNodes.push(exactFidelity(node.id, node.kind));
			pixelToFnName.set(compiled.output, fnName);
			recordTapProduct(compiled.output, 1);
			return;
		}

		const emitter = lookDctlEmitters[node.kind];
		if (!emitter) {
			bodySections.push(
				passthroughSource(
					fnName,
					upstreamFnName,
					`${lookGraphNodeLabel(node.kind)} ("${node.kind}") has no DCTL emitter in this exporter slice; passed through unchanged`,
				),
			);
			fidelityNodes.push(
				issueFidelity(
					node.id,
					node.kind,
					"unsupported",
					`dctl-${node.kind}-not-yet-supported: no DCTL emitter registered for this node kind yet`,
				),
			);
			pixelToFnName.set(compiled.output, fnName);
			recordTapProduct(compiled.output, 1);
			return;
		}

		const tapBudget = Math.max(
			1,
			Math.floor(DCTL_TAP_BUDGET / upstreamTapProduct),
		);
		const result = emitter(node, {
			builder,
			fnName,
			upstreamCall: chainCall(upstreamFnName),
			upstreamFnName,
			nodeIndex: index,
			tapBudget,
			exposeAllParams: options.exposeAllParams ?? false,
		});
		if (
			node.kind === "vhs-tracking" ||
			node.kind === "vhs-noise" ||
			node.kind === "signal-glitch" ||
			node.kind === "interlace"
		) {
			usesTimelineFrameIndex = true;
		}
		bodySections.push(result.source);
		fidelityNodes.push(result.fidelity);
		pixelToFnName.set(compiled.output, fnName);
		recordTapProduct(compiled.output, result.tapCount);
	});

	const entryUpstreamFnName =
		pixelToFnName.get(plan.outputPixel) ?? ROOT_FN_NAME;
	const report: LookDctlReport = {
		nodes: fidelityNodes,
		notes: [
			COLORSPACE_ASSUMED_NOTE,
			UV_ORIENTATION_ASSUMED_NOTE,
			...(usesTimelineFrameIndex ? [TIMELINE_FRAME_INDEX_NOTE] : []),
		],
		tapBudget: {
			budget: DCTL_TAP_BUDGET,
			worstCaseProduct: worstCaseTapProduct,
		},
	};
	const headerComment = buildHeaderComment(options.owner, report);
	const source = builder.build({
		headerComment,
		bodySections: [...bodySections, transformEntrySource(entryUpstreamFnName)],
	});
	return { source, report };
}
