# 受理済みS3v exitシーンのhero.blend生成スクリプト
# 60fps/360f=F3回避、HeroRoot π/X=F1回避
# 再生成: blender --background --python author_hero.py

"""
S3v hero authoring (headless Blender) -- REVISION 2.

Coordinate reasoning (verified against the Vecmo runtime, not assumed):
  Blender +X -> glTF +X -> screen horizontal (right)
  Blender +Z -> glTF +Y -> screen vertical
  Blender +Y -> glTF -Z -> screen depth (into screen)

Hierarchy bounding box matters: Babylon normalizes the WHOLE imported hierarchy
so its longest dimension == 1 unit, then Vecmo scales that unit box by
min(placement.width, placement.height). Every extra mesh that widens the
bounding box therefore SHRINKS the hero on screen. With the accent ring gone,
DISC_RADIUS is the only remaining on-screen-scale knob in this file.

The runtime creates no ground/floor, so a shadow is only visible if this file
supplies a receiver. A horizontal floor would be exactly edge-on under the
runtime's straight-on presentation camera, so the receiver is a VERTICAL disc
behind the hero instead.

-------------------------------------------------------------------- revision 2
Three authored defects were rejected at full resolution. Two of them are one
root cause; the fixes are recorded here so the reasoning is not lost.

R1 SPIN AXIS WAS WRONG (this caused BOTH the "limp squiggle" poses AND the
   "disc detaches and drifts" reading).
   The (p,q)=(2,3) torus knot below is generated with the substitution
     radius = cos(3t) + 2,  (x,z) = radius * (cos 2t, sin 2t),  y = -sin(3t)
   Advancing t by 2*pi/3 leaves cos(3t) and sin(3t) fixed and advances the
   (x,z) angle by 4*pi/3. The curve therefore maps onto itself under a 120
   degree rotation about BLENDER Y -- Y is the 3-fold symmetry axis, and per
   the mapping above Y is the screen DEPTH axis.
   Revision 1 keyed the spin about Z (screen-vertical), i.e. an axis lying IN
   the knot's own plane. The form is near-planar (in-plane span 6.7, out-of-
   plane span 3.2), so an in-plane spin axis swings it edge-on twice per turn:
   that is exactly the f50-70 "limp squiggle".
   It also explains the disc complaint. The disc is static and always centred
   at the origin (verified from the rejected .blend: HeroBackdrop's only parent
   is HeroRoot and it carries no animation data). What moved was the KNOT -- a
   near-planar form spun about an in-plane axis has a wandering projected
   centroid, so it sags out from behind a stationary disc. The viewer read the
   relative motion as the disc drifting.
   Fix: spin about Y (the symmetry axis / view axis). The silhouette is then
   invariant every 120 degrees and never degenerates.

R2 TILT IS NOW CONSTANT, NOT OSCILLATING. Revision 1 swept X by +/-12 degrees
   over the clip. A constant offset applied ABOVE the spin (HeroTilt is the
   spin's parent) tips the symmetry axis off the view axis so the turn reads
   as a rotating solid rather than a flat 2D spin, without reintroducing a
   second, competing motion.

R3 THE EMISSIVE ACCENT RING IS DELETED. Lifted +Z and parented under the spin,
   it orbited the hero and read as a detached floating ring. Note the knock-on
   effect: it was the composition's only cool accent, so removing it shifts the
   brass-vs-blue balance warmer. That is a deliberate, unpaid-for consequence
   of the deletion, not an oversight.
"""

import math
import sys

import bpy

# ---------------------------------------------------------------- parameters
# MEASURED, not assumed. A first build authored 0..180 at 30fps rendered TWO
# full turns across the 6s clip: captured canvas frames 0 and 90 came back
# byte-identical, and 45 and 135 likewise, i.e. a 90-frame visual period. The
# sculpture is provably not 2-fold symmetric about the spin axis, so a 90-frame
# period can only be a full 360 deg turn.
#
# Working back: Vecmo computes groupFrame = blenderFrame / linkFps * 60 with
# linkFps = the artboard's 30, so groupFrame = 2 * blenderFrame. Observing a
# full turn at Vecmo frame 90 means the turn occupies 180 group frames, which
# only holds if the exported glTF carries 60fps timing (group frame == authored
# frame). Net effect: Vecmo frame f samples authored frame 2f.
#
# So the clip is authored at 60fps across 360 frames. That is the same 6
# seconds as the 1280x720@30fps/180-frame artboard.
FPS = 60
FRAME_START = 0
FRAME_END = 360

KNOT_P, KNOT_Q = 2, 3
KNOT_SAMPLES = 256
KNOT_TUBE = 0.34
KNOT_BEVEL_RES = 4
# The 3-fold symmetry axis of the curve generated by build_knot(). See R1.
KNOT_SYMMETRY_AXIS_INDEX = 1  # Blender Y == screen depth

# Comfortably larger than the knot's 3.34 projected radius so the knot never
# overflows its own backdrop (revision 1 let the knot hang out of the bottom of
# the disc, which is what made the disc read as an unrelated blob).
DISC_RADIUS = 3.9
DISC_DEPTH = 2.6  # +Y == behind the hero (after the HeroRoot flip below)

BRASS_SRGB = (0xC8, 0x87, 0x3A)
DISC_SRGB = (0x0E, 0x13, 0x1C)

# Constant, applied ABOVE the spin. Capped at 10 by the brief.
TILT_DEGREES = 10.0

# Total spin across the clip. A multiple of the 120 degree symmetry period, so
# the last authored frame lands back on the starting appearance. (The x2 frame
# sampling means Vecmo's f0..f179 covers 238.7 of those 240 degrees, so the loop
# is effectively -- not exactly -- closed.)
SPIN_TOTAL_DEGREES = 240.0
# glTF stores rotation as quaternions and interpolates along the shortest arc,
# so any single keyed segment of >=180 degrees is ambiguous and can silently
# collapse to a no-op. 60 frames == 40 degrees here: unambiguous.
SPIN_KEY_STEP_FRAMES = 60


def srgb_to_linear(component: int) -> float:
    c = component / 255.0
    if c <= 0.04045:
        return c / 12.92
    return ((c + 0.055) / 1.055) ** 2.4


def linear_rgba(srgb):
    return (*(srgb_to_linear(v) for v in srgb), 1.0)


def principled(material):
    return next(n for n in material.node_tree.nodes if n.type == "BSDF_PRINCIPLED")


def set_input(node, names, value):
    """Blender renamed several Principled sockets across versions."""
    for name in names:
        socket = node.inputs.get(name)
        if socket is not None:
            socket.default_value = value
            return True
    return False


def make_material(name, base_srgb, metallic, roughness):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = principled(mat)
    set_input(bsdf, ("Base Color",), linear_rgba(base_srgb))
    set_input(bsdf, ("Metallic",), metallic)
    set_input(bsdf, ("Roughness",), roughness)
    # Fully opaque: alpha-blended meshes write no depth and inherit far-plane
    # CoC, which makes them permanently mis-blurred by the DOF pass.
    set_input(bsdf, ("Alpha",), 1.0)
    for attr, value in (("blend_method", "OPAQUE"), ("surface_render_method", "DITHERED")):
        if hasattr(mat, attr):
            try:
                setattr(mat, attr, value)
            except (TypeError, AttributeError):
                pass
    return mat


def build_knot():
    curve = bpy.data.curves.new("HeroKnotCurve", type="CURVE")
    curve.dimensions = "3D"
    spline = curve.splines.new("POLY")
    spline.points.add(KNOT_SAMPLES - 1)
    for i in range(KNOT_SAMPLES):
        t = 2.0 * math.pi * i / KNOT_SAMPLES
        radius = math.cos(KNOT_Q * t) + 2.0
        # generated straight into the XZ plane so the form faces the viewer;
        # Y (out of that plane) is therefore the 3-fold symmetry axis -- see R1
        x = radius * math.cos(KNOT_P * t)
        z = radius * math.sin(KNOT_P * t)
        y = -math.sin(KNOT_Q * t)
        spline.points[i].co = (x, y, z, 1.0)
    spline.use_cyclic_u = True
    curve.bevel_depth = KNOT_TUBE
    curve.bevel_resolution = KNOT_BEVEL_RES
    curve.use_fill_caps = True

    obj = bpy.data.objects.new("HeroKnot", curve)
    bpy.context.collection.objects.link(obj)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.convert(target="MESH")
    bpy.ops.object.shade_smooth()
    obj.select_set(False)
    obj.data.materials.append(
        make_material("HeroBrass", BRASS_SRGB, metallic=1.0, roughness=0.25)
    )
    return obj


def build_backdrop():
    """Vertical shadow receiver. Horizontal would be edge-on to the runtime's
    fixed straight-on presentation camera and therefore invisible."""
    bpy.ops.mesh.primitive_circle_add(
        vertices=128,
        radius=DISC_RADIUS,
        fill_type="NGON",
        location=(0.0, DISC_DEPTH, 0.0),
        rotation=(math.radians(90.0), 0.0, 0.0),
    )
    obj = bpy.context.active_object
    obj.name = "HeroBackdrop"
    obj.select_set(False)
    obj.data.materials.append(
        make_material("HeroBackdrop", DISC_SRGB, metallic=0.0, roughness=0.85)
    )
    return obj


def action_fcurves(target):
    """Blender 4.4+/5.x moved f-curves behind slotted actions; 4.x had
    Action.fcurves directly. Support both rather than pinning a version."""
    anim = target.animation_data
    action = anim.action
    if hasattr(action, "fcurves"):
        return list(action.fcurves)
    curves = []
    for layer in action.layers:
        for strip in layer.strips:
            bag = strip.channelbag(anim.action_slot)
            if bag is not None:
                curves.extend(bag.fcurves)
    return curves


def key_rotation(target, frames_values, index, interpolation):
    # Set the insert-time default too, so the keys are correct even if the
    # post-hoc f-curve walk finds nothing on a future API revision.
    bpy.context.preferences.edit.keyframe_new_interpolation_type = interpolation
    for frame, value in frames_values:
        target.rotation_euler[index] = math.radians(value)
        target.keyframe_insert("rotation_euler", index=index, frame=frame)
    for fcurve in action_fcurves(target):
        if fcurve.data_path != "rotation_euler" or fcurve.array_index != index:
            continue
        for kp in fcurve.keyframe_points:
            kp.interpolation = interpolation


def build_hierarchy():
    """root(flip) -> tilt(constant) -> spin(animated) -> knot; backdrop under
    root only, so it is completely outside the animated chain."""
    knot = build_knot()
    backdrop = build_backdrop()

    spin = bpy.data.objects.new("HeroSpin", None)
    bpy.context.collection.objects.link(spin)
    spin.empty_display_size = 1.0
    spin.rotation_mode = "XYZ"
    knot.parent = spin

    tilt = bpy.data.objects.new("HeroTilt", None)
    bpy.context.collection.objects.link(tilt)
    tilt.rotation_mode = "XYZ"
    # about X == the screen-horizontal axis, so the form leans toward the camera
    tilt.rotation_euler = (math.radians(TILT_DEGREES), 0.0, 0.0)
    spin.parent = tilt

    # MEASURED, not assumed: the placement pipeline applies a 180-degree X
    # rotation (diag(1,-1,-1)) on top of glTF data that already loaded in the
    # correct orientation, so authored "up" renders down and authored "behind"
    # renders in front. The first build put the backdrop disc in FRONT of the
    # sculpture and hid it completely. This root cancels the flip once for every
    # child, restoring both the vertical and the depth ordering.
    root = bpy.data.objects.new("HeroRoot", None)
    bpy.context.collection.objects.link(root)
    root.rotation_euler = (math.pi, 0.0, 0.0)
    for child in (tilt, backdrop):
        child.parent = root

    spin_keys = [
        (frame, frame * (SPIN_TOTAL_DEGREES / (FRAME_END - FRAME_START)))
        for frame in range(FRAME_START, FRAME_END + 1, SPIN_KEY_STEP_FRAMES)
    ]
    key_rotation(spin, spin_keys, KNOT_SYMMETRY_AXIS_INDEX, "LINEAR")
    return knot, backdrop, spin


def report_extents(objects):
    extents = {}
    deps = bpy.context.evaluated_depsgraph_get()
    for obj in objects:
        evaluated = obj.evaluated_get(deps)
        pts = [obj.matrix_world @ v.co for v in evaluated.data.vertices]
        extents[obj.name] = {
            "x": (min(p.x for p in pts), max(p.x for p in pts)),
            "y": (min(p.y for p in pts), max(p.y for p in pts)),
            "z": (min(p.z for p in pts), max(p.z for p in pts)),
        }
    for name, ext in extents.items():
        print(f"[s3v] extent {name}: {ext}")
    span = {
        axis: max(e[axis][1] for e in extents.values())
        - min(e[axis][0] for e in extents.values())
        for axis in ("x", "y", "z")
    }
    knot_z = extents["HeroKnot"]["z"][1] - extents["HeroKnot"]["z"][0]
    longest = max(span.values())
    print(f"[s3v] hierarchy span x={span['x']:.3f} y={span['y']:.3f} z={span['z']:.3f}")
    print(f"[s3v] longest={longest:.3f} knot_z={knot_z:.3f} "
          f"hero_fraction_of_placement={knot_z / longest:.3f}")


def main(out_path):
    bpy.ops.wm.read_factory_settings(use_empty=True)

    scene = bpy.context.scene
    scene.render.fps = FPS
    scene.render.fps_base = 1.0
    scene.frame_start = FRAME_START
    scene.frame_end = FRAME_END

    knot, backdrop, _spin = build_hierarchy()

    bpy.ops.wm.save_as_mainfile(filepath=out_path)
    print("[s3v] saved:", out_path)
    report_extents((knot, backdrop))


if __name__ == "__main__":
    main(sys.argv[sys.argv.index("--") + 1])
