import { execFileSync } from "node:child_process";
import {
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import path from "node:path";

/**
 * Freshness guard: proves the committed reference-scene fixtures AND their
 * paired "View export result" demo artifacts (`public/tutorial-exports/`)
 * still match what their generator sources produce. `gen:reference-scenes`
 * is byte-deterministic for both, so regenerating an in-sync library rewrites
 * the same bytes; a diff means a file was hand-edited, or a generator source
 * changed without a re-run, so the committed data has silently drifted from
 * the code that owns it.
 *
 * This is non-destructive: it snapshots both directories, regenerates once,
 * compares each, and restores the committed bytes whether it passes or fails
 * — so it is safe to run inside the default `check` chain without mutating
 * the working tree. (It still shells out to the generator, which spawns
 * Biome; the fast drift + liveness gate `check:reference-scenes` is the
 * per-edit one.)
 */

type TrackedDir = {
	readonly label: string;
	readonly relativeDir: string;
	readonly isTracked: (name: string) => boolean;
};

const TRACKED_DIRS: readonly TrackedDir[] = [
	{
		label: "fixture",
		relativeDir: "src/features/reference-scenes/fixtures",
		isTracked: (name) => name.endsWith(".fixture.ts"),
	},
	{
		// Every file under this directory is generated `gen:reference-scenes`
		// output (HTML + runtime `.js` pairs), so every name is tracked.
		label: "export-demo artifact",
		relativeDir: "public/tutorial-exports",
		isTracked: () => true,
	},
];

const snapshotDir = (dir: TrackedDir): Map<string, string> => {
	const absDir = path.join(process.cwd(), dir.relativeDir);
	mkdirSync(absDir, { recursive: true });
	const snapshot = new Map<string, string>();
	for (const name of readdirSync(absDir).filter(dir.isTracked)) {
		snapshot.set(name, readFileSync(path.join(absDir, name), "utf8"));
	}
	return snapshot;
};

const restoreDir = (dir: TrackedDir, before: Map<string, string>): void => {
	const absDir = path.join(process.cwd(), dir.relativeDir);
	const after = readdirSync(absDir).filter(dir.isTracked);
	for (const [name, content] of before) {
		writeFileSync(path.join(absDir, name), content, "utf8");
	}
	for (const name of after) {
		if (!before.has(name)) {
			rmSync(path.join(absDir, name));
		}
	}
};

const DIVERGENCE_EXCERPT_RADIUS = 80;

/** Escapes control characters so a diagnostic excerpt prints as one terminal line. */
const escapeForSingleLine = (value: string): string => JSON.stringify(value);

/**
 * Prints the index of the first differing character between the committed and
 * regenerated contents of one stale file, plus a `±80`-char excerpt around it
 * from each side, to stderr. Called from {@link staleEntriesForDir} — the only
 * place that still holds both strings — BEFORE {@link restoreDir} overwrites
 * the regenerated bytes with the committed ones, so this is the last point the
 * regenerated content is readable at all.
 */
const printFirstDivergence = (
	relativePath: string,
	committed: string,
	regenerated: string,
): void => {
	let firstDiff = 0;
	const maxLen = Math.max(committed.length, regenerated.length);
	while (
		firstDiff < maxLen &&
		committed[firstDiff] === regenerated[firstDiff]
	) {
		firstDiff += 1;
	}
	const start = Math.max(0, firstDiff - DIVERGENCE_EXCERPT_RADIUS);
	const end = firstDiff + DIVERGENCE_EXCERPT_RADIUS;
	console.error(`  ${relativePath}: first divergence at char ${firstDiff}`);
	console.error(
		`    expected(committed): ${escapeForSingleLine(committed.slice(start, end))}`,
	);
	console.error(
		`    regenerated:          ${escapeForSingleLine(regenerated.slice(start, end))}`,
	);
};

const staleEntriesForDir = (
	dir: TrackedDir,
	before: Map<string, string>,
): string[] => {
	const absDir = path.join(process.cwd(), dir.relativeDir);
	const after = readdirSync(absDir).filter(dir.isTracked);
	const stale: string[] = [];
	for (const name of after) {
		const regenerated = readFileSync(path.join(absDir, name), "utf8");
		if (!before.has(name)) {
			stale.push(
				`${dir.relativeDir}/${name} (generator emits a ${dir.label} that is not committed)`,
			);
		} else if (before.get(name) !== regenerated) {
			stale.push(`${dir.relativeDir}/${name}`);
			printFirstDivergence(
				`${dir.relativeDir}/${name}`,
				// biome-ignore lint/style/noNonNullAssertion: guarded by the `before.has(name)` branch above.
				before.get(name)!,
				regenerated,
			);
		}
	}
	for (const name of before.keys()) {
		if (!after.includes(name)) {
			stale.push(
				`${dir.relativeDir}/${name} (committed ${dir.label} is no longer generated)`,
			);
		}
	}
	return stale;
};

const beforeByDir = new Map(
	TRACKED_DIRS.map((dir) => [dir, snapshotDir(dir)] as const),
);

try {
	execFileSync("bun", ["run", "gen:reference-scenes"], {
		cwd: process.cwd(),
		stdio: "ignore",
	});
} catch (error) {
	console.error(
		"Reference-scenes freshness check failed: the generator errored.",
	);
	console.error(error instanceof Error ? error.message : String(error));
	// Restore whatever snapshots were taken before the failed run so a partial
	// generator run cannot leave the working tree mutated.
	for (const [dir, before] of beforeByDir) restoreDir(dir, before);
	process.exit(1);
}

const stale = TRACKED_DIRS.flatMap((dir) => {
	const before = beforeByDir.get(dir);
	if (!before) return [];
	return staleEntriesForDir(dir, before);
});

// Restore the committed state regardless of outcome (non-destructive check).
for (const [dir, before] of beforeByDir) restoreDir(dir, before);

if (stale.length > 0) {
	console.error(
		"Reference-scene fixtures or export-demo artifacts are out of sync with their generator sources.",
	);
	console.error(
		"A file was hand-edited, or a generator source changed without rerunning the generator.",
	);
	console.error("Run `bun run gen:reference-scenes` and commit the result.");
	console.error("");
	for (const entry of stale) {
		console.error(`  - ${entry}`);
	}
	process.exit(1);
}

console.log(
	"Reference-scenes freshness check passed (fixtures and export-demo artifacts match their generator sources).",
);
