/**
 * Shared bundler for the motion/code handoff runtime samplers.
 *
 * The exported `*.runtime.js` must sample motion with the SAME pure code the
 * editor uses, but it has to run without the build. So we esbuild-bundle the pure
 * sampler entries into self-contained IIFE strings and commit them as generated TS
 * modules that {@link ../src/features/export/model/code.ts} embeds. esbuild runs in
 * Node here; only the resulting strings ship to the browser.
 *
 * Four bundles are produced (see {@link RUNTIME_SAMPLER_BUNDLES}):
 *  - the FULL sampler ({@link ../src/features/export/model/runtime-sampler-entry.ts}),
 *  - the CORE sampler ({@link ../src/features/export/model/runtime-sampler-core-entry.ts}),
 *    which drops the motion-grammar evaluator + expression sampler for scenes that
 *    use neither (a smaller, byte-identical runtime for the common keyframe case).
 *  - the LEAN sampler ({@link ../src/features/export/model/runtime-sampler-lean-entry.ts}),
 *    which additionally drops mask/mesh-paint builders, the interaction engine,
 *    and the source-optics/effect-expression/look-graph/blend presentation
 *    stages for scenes the motion-artifact export profile's tier predicate has
 *    confirmed need none of those.
 *  - the FLAT sampler ({@link ../src/features/export/model/runtime-sampler-flat-entry.ts}),
 *    LEAN minus real camera projection, for scenes the tier predicate has
 *    confirmed have no scene-camera rig and declare `cameraSpacePolicy:
 *    "screen_2d"`.
 *
 * `generate-runtime-sampler.ts` writes the modules; `check-runtime-sampler.ts`
 * re-bundles and fails if a committed module drifted from source. Both import this
 * so the bundles are defined in exactly one place.
 */

import { existsSync } from "node:fs";
import path from "node:path";
import { build, type Plugin } from "esbuild";

const repoRoot = process.cwd();
const srcDir = path.join(repoRoot, "src");
const exportModelDir = path.join(srcDir, "features/export/model");

export const RUNTIME_SAMPLER_GLOBAL = "__vectorMotionRuntimeSampler";

/** One committed sampler bundle: a bundler entry, its generated module, and the export name. */
export type RuntimeSamplerBundle = {
	readonly entry: string;
	readonly generatedFile: string;
	readonly exportName: string;
};

export const RUNTIME_SAMPLER_BUNDLES: readonly RuntimeSamplerBundle[] = [
	{
		entry: path.join(exportModelDir, "runtime-sampler-entry.ts"),
		generatedFile: path.join(exportModelDir, "runtime-sampler.generated.ts"),
		exportName: "MOTION_RUNTIME_SAMPLER_SOURCE",
	},
	{
		entry: path.join(exportModelDir, "runtime-sampler-core-entry.ts"),
		generatedFile: path.join(
			exportModelDir,
			"runtime-sampler-core.generated.ts",
		),
		exportName: "MOTION_RUNTIME_SAMPLER_CORE_SOURCE",
	},
	{
		entry: path.join(exportModelDir, "runtime-sampler-lean-entry.ts"),
		generatedFile: path.join(
			exportModelDir,
			"runtime-sampler-lean.generated.ts",
		),
		exportName: "MOTION_RUNTIME_SAMPLER_LEAN_SOURCE",
	},
	{
		entry: path.join(exportModelDir, "runtime-sampler-flat-entry.ts"),
		generatedFile: path.join(
			exportModelDir,
			"runtime-sampler-flat.generated.ts",
		),
		exportName: "MOTION_RUNTIME_SAMPLER_FLAT_SOURCE",
	},
];

// esbuild does not read the `@/` tsconfig alias on its own; mirror the Vite alias
// so the bundled entry resolves the same modules the app does.
const aliasAtPlugin = (): Plugin => ({
	name: "alias-@",
	setup(esbuild) {
		esbuild.onResolve({ filter: /^@\// }, (args) => {
			const base = path.join(srcDir, args.path.slice(2));
			const candidates = [
				`${base}.ts`,
				`${base}.tsx`,
				path.join(base, "index.ts"),
				path.join(base, "index.tsx"),
			];
			const resolved = candidates.find((candidate) => existsSync(candidate));
			return resolved ? { path: resolved } : undefined;
		});
	},
});

/**
 * Bundles a sampler entry into one self-contained, minified IIFE string. The IIFE
 * assigns the sampler API to the {@link RUNTIME_SAMPLER_GLOBAL} binding when
 * evaluated. Deterministic for a given source + esbuild version.
 */
export async function bundleRuntimeSamplerSource(
	entry: string,
): Promise<string> {
	const result = await build({
		entryPoints: [entry],
		bundle: true,
		format: "iife",
		globalName: RUNTIME_SAMPLER_GLOBAL,
		platform: "browser",
		target: "es2020",
		minify: true,
		legalComments: "none",
		write: false,
		absWorkingDir: srcDir,
		plugins: [aliasAtPlugin()],
	});
	const text = result.outputFiles[0]?.text ?? "";
	return text.trimEnd();
}

/** Renders a committed generated module from a bundled IIFE source string. */
export function renderGeneratedModule(
	iifeSource: string,
	bundle: RuntimeSamplerBundle,
): string {
	const entryRelative = path.relative(srcDir, bundle.entry);
	return [
		"// @generated by scripts/generate-runtime-sampler.ts — DO NOT EDIT BY HAND.",
		"//",
		`// Self-contained esbuild bundle of src/${entryRelative}, embedded into the`,
		"// motion/code handoff runtime so exported playback reproduces the editor's",
		"// pure motion sampler. Regenerate with `bun run gen:runtime-sampler`;",
		"// `bun run check` fails if it drifts from source.",
		"",
		`/** Bundled IIFE source; assigns the sampler API to ${RUNTIME_SAMPLER_GLOBAL} when run. */`,
		`export const ${bundle.exportName} = ${JSON.stringify(iifeSource)};`,
		"",
	].join("\n");
}
