/**
 * Browser-runtime bundler for the WebGL player export.
 *
 * Unlike the pure runtime sampler, this entry intentionally includes DOM/WebGL
 * code: the generated player must run in a normal web page, mount one canvas,
 * rasterize the real SVG export into a texture, and drive the GPU Look graph.
 */

import { existsSync } from "node:fs";
import path from "node:path";
import { build, type Plugin } from "esbuild";

const repoRoot = process.cwd();
const srcDir = path.join(repoRoot, "src");

export const WEBGL_PLAYER_GLOBAL = "__vectorMotionWebglPlayerRuntime";
export const WEBGL_PLAYER_ENTRY = path.join(
	srcDir,
	"features/export/model/webgl-player-entry.ts",
);
export const WEBGL_PLAYER_GENERATED_FILE = path.join(
	srcDir,
	"features/export/model/webgl-player.generated.ts",
);

const aliasAtPlugin = (): Plugin => ({
	name: "alias-@",
	setup(esbuild) {
		esbuild.onResolve({ filter: /^@\// }, (args) => {
			const base = path.join(srcDir, args.path.slice(2));
			const candidates = [
				`${base}.ts`,
				`${base}.tsx`,
				path.join(base, "index.ts"),
				path.join(base, "index.tsx"),
			];
			const resolved = candidates.find((candidate) => existsSync(candidate));
			return resolved ? { path: resolved } : undefined;
		});
	},
});

/** Bundles the browser WebGL player entry into one self-contained IIFE source string. */
export async function bundleWebglPlayerSource(): Promise<string> {
	const result = await build({
		entryPoints: [WEBGL_PLAYER_ENTRY],
		bundle: true,
		format: "iife",
		globalName: WEBGL_PLAYER_GLOBAL,
		platform: "browser",
		target: "es2020",
		minify: true,
		legalComments: "none",
		write: false,
		absWorkingDir: srcDir,
		plugins: [aliasAtPlugin()],
	});
	return (result.outputFiles[0]?.text ?? "").trimEnd();
}

/** Renders the committed generated module from a bundled IIFE source string. */
export function renderGeneratedWebglPlayerModule(iifeSource: string): string {
	return [
		"// @generated by scripts/generate-webgl-player.ts - DO NOT EDIT BY HAND.",
		"//",
		"// Self-contained browser bundle of the WebGL player runtime",
		"// (src/features/export/model/webgl-player-entry.ts), embedded into the",
		"// generated webgl-player JS export.",
		"",
		"/** Bundled IIFE source; assigns the WebGL player API to a module-local binding when run. */",
		`export const WEBGL_PLAYER_RUNTIME_SOURCE = ${JSON.stringify(iifeSource)};`,
		"",
	].join("\n");
}
